# coding: utf-8

# flake8: noqa
"""
    NLP Sandbox Physical Address Annotator API

    The OpenAPI specification implemented by NLP Sandbox Physical Address Annotators. # Overview This NLP tool detects references of physical addresses in the clinical notes given as input and returns a list of physical address annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from addressannotator.models.error import Error
from addressannotator.models.note import Note
from addressannotator.models.service import Service
from addressannotator.models.text_annotation import TextAnnotation
from addressannotator.models.text_physical_address_annotation import TextPhysicalAddressAnnotation
from addressannotator.models.text_physical_address_annotation_all_of import TextPhysicalAddressAnnotationAllOf
from addressannotator.models.text_physical_address_annotation_request import TextPhysicalAddressAnnotationRequest
from addressannotator.models.text_physical_address_annotations import TextPhysicalAddressAnnotations
