"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import annotator
from annotator.model.note import Note
from annotator.models import PatientId, NoteId
globals()['Note'] = Note
from annotator.model.text_date_annotation_request import TextDateAnnotationRequest


class TestTextDateAnnotationRequest(unittest.TestCase):
    """TextDateAnnotationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextDateAnnotationRequest(self):
        """Test TextDateAnnotationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextDateAnnotationRequest()  # noqa: E501
        TextDateAnnotationRequest(
            note=Note(
                identifier=NoteId("identifier"),
                text="text", type="type",
                patient_id=PatientId('patient-1')
            )
        )


if __name__ == '__main__':
    unittest.main()
