"""
    NLP Sandbox Date Annotator API

    The OpenAPI specification implemented by NLP Sandbox Date Annotators. # Overview This NLP tool detects date references in the clinical note specified and returns a list of date annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import annotator
from annotator.api.service_api import ServiceApi  # noqa: E501


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service(self):
        """Test case for service

        Get service information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
