"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store import FhirStore
from nlpsandbox.model.page_limit import PageLimit
from nlpsandbox.model.page_of_fhir_stores_all_of import PageOfFhirStoresAllOf
from nlpsandbox.model.page_offset import PageOffset
from nlpsandbox.model.response_page_metadata import ResponsePageMetadata
from nlpsandbox.model.response_page_metadata_links import ResponsePageMetadataLinks
globals()['FhirStore'] = FhirStore
globals()['PageLimit'] = PageLimit
globals()['PageOfFhirStoresAllOf'] = PageOfFhirStoresAllOf
globals()['PageOffset'] = PageOffset
globals()['ResponsePageMetadata'] = ResponsePageMetadata
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandbox.model.page_of_fhir_stores import PageOfFhirStores


class TestPageOfFhirStores(unittest.TestCase):
    """PageOfFhirStores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfFhirStores(self):
        """Test PageOfFhirStores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfFhirStores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
