"""
    NLP Sandbox Data Node API

    # Overview  The NLP Sandbox Data Node is a repository of data used to benchmark NLP Tools like the NLP Sandbox Date Annotator and Person Name Annotator.  The resources that can be stored in this Data Node and the operations supported are listed below:  - Create and manage datasets - Create and manage FHIR stores   - Store and retrieve FHIR patient profiles   - Store and retrieve clinical   notes - Create and manage annotation stores   - Store and retrieve text annotations   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import datanode
from datanode.api.note_api import NoteApi  # noqa: E501


class TestNoteApi(unittest.TestCase):
    """NoteApi unit test stubs"""

    def setUp(self):
        self.api = NoteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_note(self):
        """Test case for create_note

        Create a note  # noqa: E501
        """
        pass

    def test_delete_note(self):
        """Test case for delete_note

        Delete a note  # noqa: E501
        """
        pass

    def test_get_note(self):
        """Test case for get_note

        Get a note  # noqa: E501
        """
        pass

    def test_list_notes(self):
        """Test case for list_notes

        List notes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
