"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import annotator
from annotator.model.patient_id import PatientId


class TestPatientId(unittest.TestCase):
    """PatientId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatientId(self):
        """Test PatientId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatientId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
