"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import nlpsandbox
from nlpsandbox.api.annotation_store_api import AnnotationStoreApi  # noqa: E501


class TestAnnotationStoreApi(unittest.TestCase):
    """AnnotationStoreApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationStoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_annotation_store(self):
        """Test case for create_annotation_store

        Create an annotation store  # noqa: E501
        """
        pass

    def test_delete_annotation_store(self):
        """Test case for delete_annotation_store

        Delete an annotation store  # noqa: E501
        """
        pass

    def test_get_annotation_store(self):
        """Test case for get_annotation_store

        Get an annotation store  # noqa: E501
        """
        pass

    def test_list_annotation_stores(self):
        """Test case for list_annotation_stores

        List the annotation stores in a dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
