"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_annotation import TextAnnotation


class TestTextAnnotation(unittest.TestCase):
    """TextAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextAnnotation(self):
        """Test TextAnnotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextAnnotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
