"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.page_limit import PageLimit
from nlpsandbox.model.page_of_patients_all_of import PageOfPatientsAllOf
from nlpsandbox.model.page_offset import PageOffset
from nlpsandbox.model.patient import Patient
from nlpsandbox.model.response_page_metadata import ResponsePageMetadata
from nlpsandbox.model.response_page_metadata_links import ResponsePageMetadataLinks
globals()['PageLimit'] = PageLimit
globals()['PageOfPatientsAllOf'] = PageOfPatientsAllOf
globals()['PageOffset'] = PageOffset
globals()['Patient'] = Patient
globals()['ResponsePageMetadata'] = ResponsePageMetadata
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandbox.model.page_of_patients import PageOfPatients


class TestPageOfPatients(unittest.TestCase):
    """PageOfPatients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfPatients(self):
        """Test PageOfPatients"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfPatients()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
