"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.patient_id import PatientId
globals()['PatientId'] = PatientId
from nlpsandbox.model.patient import Patient


class TestPatient(unittest.TestCase):
    """Patient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatient(self):
        """Test Patient"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Patient()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
