"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.tool import Tool
from nlpsandbox.model.tool_type import ToolType
globals()['Tool'] = Tool
globals()['ToolType'] = ToolType
from nlpsandbox.model.tool_dependency import ToolDependency


class TestToolDependency(unittest.TestCase):
    """ToolDependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToolDependency(self):
        """Test ToolDependency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ToolDependency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
