"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import nlpsandbox
from nlpsandbox.api.annotation_api import AnnotationApi  # noqa: E501


class TestAnnotationApi(unittest.TestCase):
    """AnnotationApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_annotation(self):
        """Test case for create_annotation

        Create an annotation  # noqa: E501
        """
        pass

    def test_delete_annotation(self):
        """Test case for delete_annotation

        Delete an annotation  # noqa: E501
        """
        pass

    def test_get_annotation(self):
        """Test case for get_annotation

        Get an annotation  # noqa: E501
        """
        pass

    def test_list_annotations(self):
        """Test case for list_annotations

        List the annotations in an annotation store  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
