"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_annotation import TextAnnotation
from nlpsandbox.model.text_id_annotation_all_of import TextIdAnnotationAllOf
globals()['TextAnnotation'] = TextAnnotation
globals()['TextIdAnnotationAllOf'] = TextIdAnnotationAllOf
from nlpsandbox.model.text_id_annotation import TextIdAnnotation


class TestTextIdAnnotation(unittest.TestCase):
    """TextIdAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextIdAnnotation(self):
        """Test TextIdAnnotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextIdAnnotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
