"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import annotator
from annotator.model.license import License
from annotator.model.tool_type import ToolType
globals()['License'] = License
globals()['ToolType'] = ToolType
from annotator.model.tool import Tool


class TestTool(unittest.TestCase):
    """Tool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTool(self):
        """Test Tool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
