"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import annotator
from annotator.model.text_physical_address_annotation import TextPhysicalAddressAnnotation
globals()['TextPhysicalAddressAnnotation'] = TextPhysicalAddressAnnotation
from annotator.model.text_physical_address_annotation_response import TextPhysicalAddressAnnotationResponse


class TestTextPhysicalAddressAnnotationResponse(unittest.TestCase):
    """TextPhysicalAddressAnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextPhysicalAddressAnnotationResponse(self):
        """Test TextPhysicalAddressAnnotationResponse"""
        TextPhysicalAddressAnnotationResponse(
            text_physical_address_annotations=[
                TextPhysicalAddressAnnotation(start=10, length=10, text="foobar", confidence=95.5)
            ]
        )



if __name__ == '__main__':
    unittest.main()
