"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_date_annotation import TextDateAnnotation
globals()['TextDateAnnotation'] = TextDateAnnotation
from nlpsandbox.model.text_date_annotation_response import TextDateAnnotationResponse


class TestTextDateAnnotationResponse(unittest.TestCase):
    """TextDateAnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextDateAnnotationResponse(self):
        """Test TextDateAnnotationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextDateAnnotationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
