"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.tool import Tool
globals()['Tool'] = Tool
from nlpsandbox.model.tool_dependencies import ToolDependencies


class TestToolDependencies(unittest.TestCase):
    """ToolDependencies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testToolDependencies(self):
        """Test ToolDependencies"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ToolDependencies()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
