"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store_id import FhirStoreId


class TestFhirStoreId(unittest.TestCase):
    """FhirStoreId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFhirStoreId(self):
        """Test FhirStoreId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FhirStoreId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
