"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_annotation import TextAnnotation
from nlpsandbox.model.text_date_annotation_all_of import TextDateAnnotationAllOf
globals()['TextAnnotation'] = TextAnnotation
globals()['TextDateAnnotationAllOf'] = TextDateAnnotationAllOf
from nlpsandbox.model.text_date_annotation import TextDateAnnotation


class TestTextDateAnnotation(unittest.TestCase):
    """TextDateAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextDateAnnotation(self):
        """Test TextDateAnnotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextDateAnnotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
