"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_id_annotation import TextIdAnnotation
globals()['TextIdAnnotation'] = TextIdAnnotation
from nlpsandbox.model.text_id_annotation_response import TextIdAnnotationResponse


class TestTextIdAnnotationResponse(unittest.TestCase):
    """TextIdAnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextIdAnnotationResponse(self):
        """Test TextIdAnnotationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextIdAnnotationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
