# coding: utf-8

"""
    NLP Sandbox Person Name Annotator API

    The OpenAPI specification implemented by NLP Sandbox Person Name Annotators. # Overview This NLP tool detects references of person names in the clinical notes given as input and returns a list of person name annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import personannotator
from personannotator.api.text_person_name_annotation_api import TextPersonNameAnnotationApi  # noqa: E501
from personannotator.rest import ApiException


class TestTextPersonNameAnnotationApi(unittest.TestCase):
    """TextPersonNameAnnotationApi unit test stubs"""

    def setUp(self):
        self.api = personannotator.api.text_person_name_annotation_api.TextPersonNameAnnotationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_text_person_name_annotations(self):
        """Test case for create_text_person_name_annotations

        Annotate person names in a clinical note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
