"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.note_resource_name import NoteResourceName
globals()['NoteResourceName'] = NoteResourceName
from nlpsandbox.model.note_create_response import NoteCreateResponse


class TestNoteCreateResponse(unittest.TestCase):
    """NoteCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteCreateResponse(self):
        """Test NoteCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NoteCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
