"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation import Annotation
globals()['Annotation'] = Annotation
from nlpsandbox.model.page_of_annotations_all_of import PageOfAnnotationsAllOf


class TestPageOfAnnotationsAllOf(unittest.TestCase):
    """PageOfAnnotationsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfAnnotationsAllOf(self):
        """Test PageOfAnnotationsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfAnnotationsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
