"""
    NLP Sandbox Data Node API

    # Overview  The NLP Sandbox Data Node is a repository of data used to benchmark NLP Tools like the NLP Sandbox Date Annotator and Person Name Annotator.  The resources that can be stored in this Data Node and the operations supported are listed below:  - Create and manage datasets - Create and manage FHIR stores   - Store and retrieve FHIR patient profiles   - Store and retrieve clinical   notes - Create and manage annotation stores   - Store and retrieve text annotations   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandboxsdk
from nlpsandboxsdk.model.annotation_store import AnnotationStore
from nlpsandboxsdk.model.page_limit import PageLimit
from nlpsandboxsdk.model.page_of_annotation_stores_all_of import PageOfAnnotationStoresAllOf
from nlpsandboxsdk.model.page_offset import PageOffset
from nlpsandboxsdk.model.response_page_metadata import ResponsePageMetadata
from nlpsandboxsdk.model.response_page_metadata_links import ResponsePageMetadataLinks
from nlpsandboxsdk.models import AnnotationStoreName
globals()['AnnotationStore'] = AnnotationStore
globals()['PageLimit'] = PageLimit
globals()['PageOfAnnotationStoresAllOf'] = PageOfAnnotationStoresAllOf
globals()['PageOffset'] = PageOffset
globals()['ResponsePageMetadata'] = ResponsePageMetadata
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandboxsdk.model.page_of_annotation_stores import PageOfAnnotationStores


class TestPageOfAnnotationStores(unittest.TestCase):
    """PageOfAnnotationStores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfAnnotationStores(self):
        """Test PageOfAnnotationStores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfAnnotationStores()  # noqa: E501
        PageOfAnnotationStores(
            offset=PageOffset(3),
            limit=PageLimit(10),
            total_results=4,
            links=ResponsePageMetadataLinks(next="next"),
            annotation_stores=[AnnotationStore(name=AnnotationStoreName("name"))]
        )


if __name__ == '__main__':
    unittest.main()
