"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.note import Note
globals()['Note'] = Note
from nlpsandbox.model.text_contact_annotation_request import TextContactAnnotationRequest


class TestTextContactAnnotationRequest(unittest.TestCase):
    """TextContactAnnotationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextContactAnnotationRequest(self):
        """Test TextContactAnnotationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextContactAnnotationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
