"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_person_name_annotation import TextPersonNameAnnotation
globals()['TextPersonNameAnnotation'] = TextPersonNameAnnotation
from nlpsandbox.model.text_person_name_annotation_response import TextPersonNameAnnotationResponse


class TestTextPersonNameAnnotationResponse(unittest.TestCase):
    """TextPersonNameAnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextPersonNameAnnotationResponse(self):
        """Test TextPersonNameAnnotationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextPersonNameAnnotationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
