"""
    NLP Sandbox Data Node API

    # Overview  The NLP Sandbox Data Node is a repository of data used to benchmark NLP Tools like the NLP Sandbox Date Annotator and Person Name Annotator.  The resources that can be stored in this Data Node and the operations supported are listed below:  - Create and manage datasets - Create and manage FHIR stores   - Store and retrieve FHIR patient profiles   - Store and retrieve clinical   notes - Create and manage annotation stores   - Store and retrieve text annotations   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store_name import FhirStoreName
globals()['FhirStoreName'] = FhirStoreName
from nlpsandbox.model.fhir_store_create_response import FhirStoreCreateResponse


class TestFhirStoreCreateResponse(unittest.TestCase):
    """FhirStoreCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFhirStoreCreateResponse(self):
        """Test FhirStoreCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FhirStoreCreateResponse()  # noqa: E501
        FhirStoreCreateResponse(name=FhirStoreName("name"))


if __name__ == '__main__':
    unittest.main()
