"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import nlpsandbox
from nlpsandbox.api.text_date_annotation_api import TextDateAnnotationApi  # noqa: E501


class TestTextDateAnnotationApi(unittest.TestCase):
    """TextDateAnnotationApi unit test stubs"""

    def setUp(self):
        self.api = TextDateAnnotationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_text_date_annotations(self):
        """Test case for create_text_date_annotations

        Annotate dates in a clinical note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
