"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import nlpsandbox
from nlpsandbox.api.note_api import NoteApi  # noqa: E501


class TestNoteApi(unittest.TestCase):
    """NoteApi unit test stubs"""

    def setUp(self):
        self.api = NoteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_note(self):
        """Test case for create_note

        Create a note  # noqa: E501
        """
        pass

    def test_delete_note(self):
        """Test case for delete_note

        Delete a note  # noqa: E501
        """
        pass

    def test_get_note(self):
        """Test case for get_note

        Get a note  # noqa: E501
        """
        pass

    def test_list_notes(self):
        """Test case for list_notes

        List notes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
