"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.text_location_annotation import TextLocationAnnotation
globals()['TextLocationAnnotation'] = TextLocationAnnotation
from nlpsandbox.model.text_location_annotation_response import TextLocationAnnotationResponse


class TestTextLocationAnnotationResponse(unittest.TestCase):
    """TextLocationAnnotationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextLocationAnnotationResponse(self):
        """Test TextLocationAnnotationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextLocationAnnotationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
