"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store import FhirStore
globals()['FhirStore'] = FhirStore
from nlpsandbox.model.page_of_fhir_stores_all_of import PageOfFhirStoresAllOf


class TestPageOfFhirStoresAllOf(unittest.TestCase):
    """PageOfFhirStoresAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfFhirStoresAllOf(self):
        """Test PageOfFhirStoresAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfFhirStoresAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
