"""
    NLP Sandbox Data Node API

    # Overview  The NLP Sandbox Data Node is a repository of data used to benchmark NLP Tools like the NLP Sandbox Date Annotator and Person Name Annotator.  The resources that can be stored in this Data Node and the operations supported are listed below:  - Create and manage datasets - Create and manage FHIR stores   - Store and retrieve FHIR patient profiles   - Store and retrieve clinical   notes - Create and manage annotation stores   - Store and retrieve text annotations   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datanode
from datanode.model.resource_source import ResourceSource
from datanode.model.annotation_source import AnnotationSource
from datanode.model.text_date_annotation import TextDateAnnotation
from datanode.model.text_person_name_annotation import TextPersonNameAnnotation
from datanode.model.text_physical_address_annotation import TextPhysicalAddressAnnotation
globals()['AnnotationSource'] = AnnotationSource
globals()['TextDateAnnotation'] = TextDateAnnotation
globals()['TextPersonNameAnnotation'] = TextPersonNameAnnotation
globals()['TextPhysicalAddressAnnotation'] = TextPhysicalAddressAnnotation
from datanode.model.annotation_create_request import AnnotationCreateRequest


class TestAnnotationCreateRequest(unittest.TestCase):
    """AnnotationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationCreateRequest(self):
        """Test AnnotationCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationCreateRequest()  # noqa: E501
        model = AnnotationCreateRequest(
            annotation_source=AnnotationSource(resource_source=ResourceSource("foo")),
            text_date_annotations=[
                TextDateAnnotation(start=10, length=10, text="foobar", confidence=95.5)
            ],
            text_person_name_annotations=[
                TextPersonNameAnnotation(start=10, length=10, text="foobar", confidence=95.5)
            ],
            text_physical_address_annotations=[
                TextPhysicalAddressAnnotation(start=10, length=10, text="foobar", confidence=95.5)
            ]
        )


if __name__ == '__main__':
    unittest.main()
