"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.patient_id import PatientId
globals()['PatientId'] = PatientId
from nlpsandbox.model.note_create_request import NoteCreateRequest


class TestNoteCreateRequest(unittest.TestCase):
    """NoteCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteCreateRequest(self):
        """Test NoteCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NoteCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
