"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation import Annotation
from nlpsandbox.model.page_limit import PageLimit
from nlpsandbox.model.page_of_annotations_all_of import PageOfAnnotationsAllOf
from nlpsandbox.model.page_offset import PageOffset
from nlpsandbox.model.response_page_metadata import ResponsePageMetadata
from nlpsandbox.model.response_page_metadata_links import ResponsePageMetadataLinks
globals()['Annotation'] = Annotation
globals()['PageLimit'] = PageLimit
globals()['PageOfAnnotationsAllOf'] = PageOfAnnotationsAllOf
globals()['PageOffset'] = PageOffset
globals()['ResponsePageMetadata'] = ResponsePageMetadata
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandbox.model.page_of_annotations import PageOfAnnotations


class TestPageOfAnnotations(unittest.TestCase):
    """PageOfAnnotations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfAnnotations(self):
        """Test PageOfAnnotations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfAnnotations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
