"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation_store import AnnotationStore
from nlpsandbox.model.page_limit import PageLimit
from nlpsandbox.model.page_of_annotation_stores_all_of import PageOfAnnotationStoresAllOf
from nlpsandbox.model.page_offset import PageOffset
from nlpsandbox.model.response_page_metadata import ResponsePageMetadata
from nlpsandbox.model.response_page_metadata_links import ResponsePageMetadataLinks
globals()['AnnotationStore'] = AnnotationStore
globals()['PageLimit'] = PageLimit
globals()['PageOfAnnotationStoresAllOf'] = PageOfAnnotationStoresAllOf
globals()['PageOffset'] = PageOffset
globals()['ResponsePageMetadata'] = ResponsePageMetadata
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandbox.model.page_of_annotation_stores import PageOfAnnotationStores


class TestPageOfAnnotationStores(unittest.TestCase):
    """PageOfAnnotationStores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfAnnotationStores(self):
        """Test PageOfAnnotationStores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfAnnotationStores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
