"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store_name import FhirStoreName


class TestFhirStoreName(unittest.TestCase):
    """FhirStoreName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFhirStoreName(self):
        """Test FhirStoreName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FhirStoreName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
