"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import nlpsandbox
from nlpsandbox.api.patient_api import PatientApi  # noqa: E501


class TestPatientApi(unittest.TestCase):
    """PatientApi unit test stubs"""

    def setUp(self):
        self.api = PatientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_patient(self):
        """Test case for create_patient

        Create a FHIR patient  # noqa: E501
        """
        pass

    def test_delete_patient(self):
        """Test case for delete_patient

        Delete a FHIR patient  # noqa: E501
        """
        pass

    def test_get_patient(self):
        """Test case for get_patient

        Get a FHIR patient  # noqa: E501
        """
        pass

    def test_list_patients(self):
        """Test case for list_patients

        List the Patients in a FHIR store  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
