"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.resource_source import ResourceSource
globals()['ResourceSource'] = ResourceSource
from nlpsandbox.model.annotation_source import AnnotationSource


class TestAnnotationSource(unittest.TestCase):
    """AnnotationSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationSource(self):
        """Test AnnotationSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
