"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.license import License


class TestLicense(unittest.TestCase):
    """License unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicense(self):
        """Test License"""
        # FIXME: construct object with mandatory attributes with example values
        # model = License()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
