"""
    NLP Sandbox Date Annotator API

    # Overview The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import annotator
from annotator.model.text_annotation import TextAnnotation
from annotator.model.text_covid_symptom_annotation_all_of import TextCovidSymptomAnnotationAllOf
globals()['TextAnnotation'] = TextAnnotation
globals()['TextCovidSymptomAnnotationAllOf'] = TextCovidSymptomAnnotationAllOf
from annotator.model.text_covid_symptom_annotation import TextCovidSymptomAnnotation


class TestTextCovidSymptomAnnotation(unittest.TestCase):
    """TextCovidSymptomAnnotation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextCovidSymptomAnnotation(self):
        """Test TextCovidSymptomAnnotation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TextCovidSymptomAnnotation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
