"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation_id import AnnotationId


class TestAnnotationId(unittest.TestCase):
    """AnnotationId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationId(self):
        """Test AnnotationId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
