"""
    NLP Sandbox Date Annotator API

    The OpenAPI specification implemented by NLP Sandbox Date Annotators. # Overview This NLP tool detects date references in the clinical note specified and returns a list of date annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import unittest

import annotator
from annotator.api.text_date_annotation_api import TextDateAnnotationApi  # noqa: E501


class TestTextDateAnnotationApi(unittest.TestCase):
    """TextDateAnnotationApi unit test stubs"""

    def setUp(self):
        self.api = TextDateAnnotationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_text_date_annotations(self):
        """Test case for create_text_date_annotations

        Annotate dates in a clinical note  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
