"""
    NLP Sandbox Data Node API

    # Overview The NLP Sandbox Data Node is a repository of data used to developed and benchmark NLP Tools like the Date Annotator and Person Name Annotator. The resources that can be stored in a Data Node are listed below: - Datasets   - FHIR Stores     - Patients     - Clinical Notes   - Annotation Stores     - Annotations   # noqa: E501

    The version of the OpenAPI document: 0.3.1
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import datanode
from datanode.model.fhir_store_name import FhirStoreName


class TestFhirStoreName(unittest.TestCase):
    """FhirStoreName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFhirStoreName(self):
        """Test FhirStoreName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FhirStoreName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
