"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.page_offset import PageOffset


class TestPageOffset(unittest.TestCase):
    """PageOffset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOffset(self):
        """Test PageOffset"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOffset()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
