"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation_name import AnnotationName
globals()['AnnotationName'] = AnnotationName
from nlpsandbox.model.annotation_create_response import AnnotationCreateResponse


class TestAnnotationCreateResponse(unittest.TestCase):
    """AnnotationCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationCreateResponse(self):
        """Test AnnotationCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
