"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.page_limit import PageLimit
from nlpsandbox.model.page_offset import PageOffset
from nlpsandbox.model.response_page_metadata_links import ResponsePageMetadataLinks
globals()['PageLimit'] = PageLimit
globals()['PageOffset'] = PageOffset
globals()['ResponsePageMetadataLinks'] = ResponsePageMetadataLinks
from nlpsandbox.model.response_page_metadata import ResponsePageMetadata


class TestResponsePageMetadata(unittest.TestCase):
    """ResponsePageMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponsePageMetadata(self):
        """Test ResponsePageMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponsePageMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
