"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.note import Note
globals()['Note'] = Note
from nlpsandbox.model.page_of_notes_all_of import PageOfNotesAllOf


class TestPageOfNotesAllOf(unittest.TestCase):
    """PageOfNotesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageOfNotesAllOf(self):
        """Test PageOfNotesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageOfNotesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
