"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.note_id import NoteId
from nlpsandbox.model.patient_id import PatientId
globals()['NoteId'] = NoteId
globals()['PatientId'] = PatientId
from nlpsandbox.model.note import Note


class TestNote(unittest.TestCase):
    """Note unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNote(self):
        """Test Note"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Note()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
