"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.fhir_store_name import FhirStoreName
globals()['FhirStoreName'] = FhirStoreName
from nlpsandbox.model.fhir_store import FhirStore


class TestFhirStore(unittest.TestCase):
    """FhirStore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFhirStore(self):
        """Test FhirStore"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FhirStore()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
