"""
    NLP Sandbox API

    NLP Sandbox REST API  # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Contact: team@nlpsandbox.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nlpsandbox
from nlpsandbox.model.annotation_store_name import AnnotationStoreName
globals()['AnnotationStoreName'] = AnnotationStoreName
from nlpsandbox.model.annotation_store import AnnotationStore


class TestAnnotationStore(unittest.TestCase):
    """AnnotationStore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationStore(self):
        """Test AnnotationStore"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AnnotationStore()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
