# coding: utf-8

"""
    NLP Sandbox Date Annotator API

    The OpenAPI specification implemented by NLP Sandbox Annotators.   # noqa: E501

    The version of the OpenAPI document: 0.3.1
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from annotator.configuration import Configuration


class TextPhysicalAddressAnnotations(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'text_physical_address_annotations': 'list[TextPhysicalAddressAnnotation]'
    }

    attribute_map = {
        'text_physical_address_annotations': 'textPhysicalAddressAnnotations'
    }

    def __init__(self, text_physical_address_annotations=None, local_vars_configuration=None):  # noqa: E501
        """TextPhysicalAddressAnnotations - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._text_physical_address_annotations = None
        self.discriminator = None

        if text_physical_address_annotations is not None:
            self.text_physical_address_annotations = text_physical_address_annotations

    @property
    def text_physical_address_annotations(self):
        """Gets the text_physical_address_annotations of this TextPhysicalAddressAnnotations.  # noqa: E501

        A list of text physical address annotations  # noqa: E501

        :return: The text_physical_address_annotations of this TextPhysicalAddressAnnotations.  # noqa: E501
        :rtype: list[TextPhysicalAddressAnnotation]
        """
        return self._text_physical_address_annotations

    @text_physical_address_annotations.setter
    def text_physical_address_annotations(self, text_physical_address_annotations):
        """Sets the text_physical_address_annotations of this TextPhysicalAddressAnnotations.

        A list of text physical address annotations  # noqa: E501

        :param text_physical_address_annotations: The text_physical_address_annotations of this TextPhysicalAddressAnnotations.  # noqa: E501
        :type: list[TextPhysicalAddressAnnotation]
        """

        self._text_physical_address_annotations = text_physical_address_annotations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TextPhysicalAddressAnnotations):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TextPhysicalAddressAnnotations):
            return True

        return self.to_dict() != other.to_dict()
