# coding: utf-8

# flake8: noqa
"""
    NLP Sandbox Person Name Annotator API

    The OpenAPI specification implemented by NLP Sandbox Person Name Annotators. # Overview This NLP tool detects references of person names in the clinical notes given as input and returns a list of person name annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from personannotator.models.error import Error
from personannotator.models.note import Note
from personannotator.models.service import Service
from personannotator.models.text_annotation import TextAnnotation
from personannotator.models.text_person_name_annotation import TextPersonNameAnnotation
from personannotator.models.text_person_name_annotation_request import TextPersonNameAnnotationRequest
from personannotator.models.text_person_name_annotations import TextPersonNameAnnotations
