# coding: utf-8

# flake8: noqa

"""
    NLP Sandbox Person Name Annotator API

    The OpenAPI specification implemented by NLP Sandbox Person Name Annotators. # Overview This NLP tool detects references of person names in the clinical notes given as input and returns a list of person name annotations.   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from personannotator.api.service_api import ServiceApi
from personannotator.api.text_person_name_annotation_api import TextPersonNameAnnotationApi

# import ApiClient
from personannotator.api_client import ApiClient
from personannotator.configuration import Configuration
from personannotator.exceptions import OpenApiException
from personannotator.exceptions import ApiTypeError
from personannotator.exceptions import ApiValueError
from personannotator.exceptions import ApiKeyError
from personannotator.exceptions import ApiException
# import models into sdk package
from personannotator.models.error import Error
from personannotator.models.note import Note
from personannotator.models.service import Service
from personannotator.models.text_annotation import TextAnnotation
from personannotator.models.text_person_name_annotation import TextPersonNameAnnotation
from personannotator.models.text_person_name_annotation_request import TextPersonNameAnnotationRequest
from personannotator.models.text_person_name_annotations import TextPersonNameAnnotations

