# coding: utf-8

"""
    NLP Sandbox Data Node API

    The OpenAPI specification implemented by NLP Sandbox Data Nodes. # Overview A NLP Sandbox Data Node is a repository of clinical notes that implements this OpenAPI specification so that other services in the NLP Sandbox ecosystem can access them. For example, a client requests data from a Data Node before passing them as input to an NLP Tool like a Date Annotator, Person Name Annotator, etc. For the sake of benchmarking NLP Tool, a Data Node can also give access to the gold standard that the NLP Tool is expected to infer (e.g. annotations).   # noqa: E501

    The version of the OpenAPI document: 0.2.2
    Contact: thomas.schaffter@sagebionetworks.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from datanodeclient.configuration import Configuration


class PageOfAnnotationStoresAllOf(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'annotation_stores': 'list[AnnotationStore]'
    }

    attribute_map = {
        'annotation_stores': 'annotationStores'
    }

    def __init__(self, annotation_stores=None, local_vars_configuration=None):  # noqa: E501
        """PageOfAnnotationStoresAllOf - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._annotation_stores = None
        self.discriminator = None

        if annotation_stores is not None:
            self.annotation_stores = annotation_stores

    @property
    def annotation_stores(self):
        """Gets the annotation_stores of this PageOfAnnotationStoresAllOf.  # noqa: E501

        An array of annotation stores  # noqa: E501

        :return: The annotation_stores of this PageOfAnnotationStoresAllOf.  # noqa: E501
        :rtype: list[AnnotationStore]
        """
        return self._annotation_stores

    @annotation_stores.setter
    def annotation_stores(self, annotation_stores):
        """Sets the annotation_stores of this PageOfAnnotationStoresAllOf.

        An array of annotation stores  # noqa: E501

        :param annotation_stores: The annotation_stores of this PageOfAnnotationStoresAllOf.  # noqa: E501
        :type: list[AnnotationStore]
        """

        self._annotation_stores = annotation_stores

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PageOfAnnotationStoresAllOf):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PageOfAnnotationStoresAllOf):
            return True

        return self.to_dict() != other.to_dict()
